### ISSUE TITLE
Refine `RelatedItem` definition

### ISSUE THREAD

**Issue by caufieldjh** [bioenergy-research-centers/brc-schema#16]
The `RelatedItem` class is currently defined as three strings:

```yaml
  RelatedItem:
    attributes:
      title:
        range: string
        description: "Title of the related item."
        slot_uri: dcterms:title
      relatedItemType:
        range: string
        description: "Type of the related item, e.g., JournalArticle."
      relatedItemIdentifier:
        range: string
        description: "Identifier or URL for the related item."
```

the item type can conceivably be an enum and the identifier should have some structure, including URL or other known ID format.

e.g., here's a CABBI example:
```json
	"RelatedItem": {
		"Title": "Metabolite discovery through global annotation of untargeted metabolomics data",
		"relatedItemType": "JournalArticle",
		"relatedItemIdentifier": "https://doi.org/10.1038/s41592-021-01303-3"
	},

```

and CBI:

```json
		"RelatedItem": {
			"Title": "GWAS supported by computer vision identifies large numbers of candidate regulators of in planta regeneration in Populus trichocarpa",
			"relatedItemType": "JournalArticle",
			"relatedItemIdentifier": "https://dx.doi.org/10.1093/g3journal/kae026"
		},
```
